### PR TITLE
[FIX] Refactor keep-alive to remove excessive calls to UserPresence

### LINKED ISSUE #498: Stop telling server alive every 10 seconds
## My Setup
- Operating System: All
- App Version: Current

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
https://github.com/RocketChat/Rocket.Chat.Electron/blob/master/src/public/preload.js#L78
We call UserPresence:online every 10 seconds on the server

### Current Behavior
Above :top:

### Expected Behavior
We need to be nice to servers and only call it when it needs to update.

Ideally I step away from computer and it should quickly put connection status to away.

So something like:
```
// No sense in setting to online if idleTime is increasing
if idleTime < lastIdleTime {
  if idleTime =< AWAY_TIME {
    // Add some kinda check.. to keep from calling again so soon. We should never call every single loop.
  } else if idleTime >= AWAY_TIME {
    // Set away
  }
```

### PR DESCRIPTION
**Pull request by gdelavald**
@RocketChat/core 

Closes #498

Refactor the code so instead of sending a keep alive every 10 seconds, we actually manage user presence status in the app. Every 10 seconds we still check if the user is idle or not, but only call Meteor when we change states.

### CODE REVIEW

File: src/public/preload.js [hunk 1]
```diff
@@ -15,6 +15,29 @@ events.forEach(function (e) {
     });
 });
 
+const userPresenceControl = () => {
+    UserPresence.stopTimer(); //stop userpresence control
+    const AWAY_TIME = 300000; // 5 min
```
Comment (geekgonecrazy) [inline src/public/preload.js]: I wonder if since we are managing we should decrease this.  I assume system idle is going to take into account mouse movements and stuff right?

Comment (gdelavald) [inline src/public/preload.js]: Yeah any kind of interaction really. Why do you feel like this should be lower? One thing we could do is add a setting, but I don't think we have any kind of "app setting" at the moment, maybe in 3.0

File: src/public/preload.js [hunk 2]
```diff
@@ -15,6 +15,29 @@ events.forEach(function (e) {
...
+    let userOnline = true;
+    setInterval(() => {
+        try {
+            const idleTime = ipcRenderer.sendSync('getSystemIdleTime');
+            if (idleTime < AWAY_TIME && !userOnline) {
+                Meteor.call('UserPresence:online');
+                userOnline = true;
+            }
+            if (idleTime >= AWAY_TIME && userOnline) {
+                if (!userOnline) { return; }
```
Comment (sampaiodiego) [inline src/public/preload.js]: this condition will never happen, since you're testing `userOnline` on the line before

**Comment by sampaiodiego** [comment]
why did you replicate the rocket.chat's user presence logic instead just using it's methods?

File: src/public/preload.js (hunk 2 above)
Comment (gdelavald) [inline src/public/preload.js]: My bad, forgot to remove this after the latest change.

**Comment by gdelavald** [comment]
I tried using the restartTimer every 10s but it was not resetting user to online once it was away.

**Comment by sampaiodiego** [comment]
oh, right.. looking at the code, looks like you need to call `UserPresence.setOnline()`.. this is also what I'm calling on the refactor btw

**Comment by gdelavald** [comment]
@geekgonecrazy with the new logic in place (just calling the `SetOnline()`) I think you have a point on lowering the timer, there is no need to have a separate thing there, since the actual timer will be controlled by the UserPresence. If we keep the AWAY_TIMER as 5 mins it would actually double the 'time to away' of the user.
I think keeping only one value and checking if there was a movement in the meantime of the interval is enough:
> if (idleTime < INTERVAL) { UserPresence.setOnline(); }
