### PR TITLE
fix: Jitsi screen sharing

### LINKED ISSUE #2028: [Bug][Jitsi][Regression] Sharing stop working since 3.7.0
## My Setup

- Operating System: Windows 10 1809
- App Version: 3.2.0
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
First that bug was described in https://github.com/RocketChat/Rocket.Chat.Electron/issues/1421 (introduced in 2.16.0 and solved in 2.17.3 with https://github.com/RocketChat/Rocket.Chat.Electron/pull/1486)
It reappeared in 3.2.0

## Step to reproduce
1. Start Jitsi call
2. Start desktop sharing

### Current Behavior
image
image

### Expected Behavior
Monitor sharing works fine as well as any application sharing

### LINKED ISSUE #2249: Screen-sharing macOS
The Video Call (Jitsi Meet) Screen-sharing with version 3.7.0 under macOS doesn't work anymore.

### PR DESCRIPTION
**Pull request by jeanfbrito**
Closes #2249
Closes #2028

### CODE REVIEW

File: src/ui/main/serverView/index.ts [hunk 1]
```diff
@@ -208,8 +208,16 @@ export const attachGuestWebContentsEvents = async (): Promise<void> => {
...
+
         const newWindow = new BrowserWindow({
-          ...options,
+          ...(isJitsiMeet
+            ? {
+                webPreferences: {
+                  preload: path.join(app.getAppPath(), 'app/preload.js'),
+                },
+              }
+            : { ...options }),
```
Comment (ggazzo) [inline src/ui/main/serverView/index.ts:220]:
```suggestion
            : options),
```

**Review by ggazzo — APPROVED** [review]
