### PR TITLE
Tray Title Windows fixed

### LINKED ISSUE #115: Refactor tray functionality
With @rodrigok agreed I open this issue to have a place for the discussion about the tray functionality of the application.

From my point of view - as windows user ;) - the following functionalities are kinda necessary:
- [x] Double click to toggle the application (on all plattforms)
- [x] Shouldn't crash anymore #109
- [ ] Number of mentions on the tray icon on all plattforms

And these menu points:
- Show (first item in the list) <- Do we even need this?
- Quit (last item in the list)
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31345076-refactor-tray-functionality?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by monspid**
# Tray Title Windows fixed #374
## Description 
There is added a title functionality for Windows applications. There are 12 new images which are loaded when messages are received.

@RocketChat/core 

Closes #115 

### TODO
We need a template for tray icons.

### Example
tray

### CODE REVIEW

File: src/scripts/tray.js [hunk 1]
```diff
@@ -24,6 +24,17 @@ const icons = {
 
 const _iconTray = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].icon || 'icon-tray.png');
 const _iconTrayAlert = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconAlert || 'icon-tray-alert.png');
+const _iconTrayTitleDot = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitleDot || 'title/icon-tray-title-dot.png');
```
Comment (alexbrazier) [inline src/scripts/tray.js]: Is there a difference between the linux and windows icons? If not you might as well put them all in a parent folder.

File: src/scripts/tray.js [hunk 2]
```diff
@@ -87,23 +98,63 @@ function createAppTray () {
...
 
+function setTitle (title) {
+    switch (title) {
+        case "":
+            mainWindow.tray.setImage(_iconTray);
+            break;
+        case "•":
+            mainWindow.tray.setImage(_iconTrayTitleDot);
+            break;
+        case "1":
```
Comment (alexbrazier) [inline src/scripts/tray.js]: Instead of having all these cases could you just generate the icon name by just using the title for all numbers e.g `` `baseName${title}.png` ``

File: src/scripts/tray.js [hunk 3]
```diff
@@ -87,23 +98,63 @@ function createAppTray () {
     };
 }
 
+function setTitle (title) {
```
Comment (alexbrazier) [inline src/scripts/tray.js]: This function is called `setTitle` but it is setting the icon image

File: src/scripts/tray.js (hunk 1 above)
Comment (monspid) [inline src/scripts/tray.js]: Actually they are just examples. They do not look good. In linux they should be 44x38 px. Now they have 32x32

File: src/scripts/tray.js (hunk 3 above)
Comment (monspid) [inline src/scripts/tray.js]: I did not know how to call it. I decided to call it setTitle, because it does what the function on OSx does - set a picture with some title. In our situation it is mostly a number for pictures. I can change the name to setImage or something like this.

File: src/scripts/tray.js (hunk 2 above)
Comment (monspid) [inline src/scripts/tray.js]: Do you want me to delete all of these?
```
const _iconTrayTitleDot = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitleDot || 'title/icon-tray-title-dot.png');
const _iconTrayTitle1 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle1 || 'title/icon-tray-title-1.png');
const _iconTrayTitle2 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle2 || 'title/icon-tray-title-2.png');
const _iconTrayTitle3 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle3 || 'title/icon-tray-title-3.png');
const _iconTrayTitle4 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle4 || 'title/icon-tray-title-4.png');
const _iconTrayTitle5 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle5 || 'title/icon-tray-title-5.png');
const _iconTrayTitle6 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle6 || 'title/icon-tray-title-6.png');
const _iconTrayTitle7 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle7 || 'title/icon-tray-title-7.png');
const _iconTrayTitle8 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle8 || 'title/icon-tray-title-8.png');
const _iconTrayTitle9 = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle9 || 'title/icon-tray-title-9.png');
const _iconTrayTitle9Plus = path.join(__dirname, 'images', icons[process.platform].dir, icons[process.platform].iconTrayTitle9Plus || 'title/icon-tray-title-9-plus.png');

```

**Comment by rodrigok** [comment]
@alexbrazier Can you review this again?

File: src/scripts/tray.js [hunk 4]
```diff
@@ -87,23 +87,34 @@ function createAppTray () {
...
 }
 
+function setImage (title) {
+    if (title === '•') {
+        title = "Dot";
+    } else if (!isNaN(parseInt(title)) && title > 9) {
+        title = "9Plus";
+    }
+
+    const _iconPath = path.join(__dirname, 'images', icons[process.platform].dir, `icon-tray${title}.png`);
```
Comment (alexbrazier) [inline src/scripts/tray.js]: This will only work for linux now that you have deleted the windows icons. If the icons are the same then you should just remove the platform dir, and put them in a parent folder.

File: src/scripts/tray.js [hunk 5]
```diff
@@ -87,23 +87,34 @@ function createAppTray () {
...
+    if (process.platform !== 'darwin') {
+        setImage(title);
     } else {
-        mainWindow.tray.setImage(_iconTray);
-        if (process.platform === 'darwin') {
-            mainWindow.tray.setTitle(title);
+        if (showAlert) {
+            mainWindow.tray.setImage(_iconTrayAlert);
+        } else {
+            mainWindow.tray.setImage(_iconTray);
```
Comment (alexbrazier) [inline src/scripts/tray.js]: It doesnt look like you are restoring the default icon tray for windows and linux when there are no notifications.

File: src/scripts/tray.js (hunk 4 above)
Comment (monspid) [inline src/scripts/tray.js]: Sorry I messed up something with commits. Icons are the same because im not good at graphic someone should change it. They should have diferent sizes.

File: src/scripts/tray.js (hunk 5 above)
Comment (monspid) [inline src/scripts/tray.js]: Maybe I'm wrong but the default icon is `icon-tray.png`. If there is no notification then the title is `""` so `icon-tray${title}.png` will be  `icon-tray.png` and this is what we wanted.

Comment (alexbrazier) [inline src/scripts/tray.js]: You are correct, I missed that 😄

File: src/scripts/tray.js (hunk 4 above)
Comment (monspid) [inline src/scripts/tray.js]: I added new icons for windows and linux, Now they look better in my opinion. @alexbrazier check this.
