### PR TITLE
fix: After zoom/reset navigating displays "white screen"

### LINKED ISSUE #1936: [Bug] When reset zoom, click room/user on sidebar display white screen
## My Setup

- Operating System: Mac
- App Version: 3.0.0-develop
- Installation type: development (yarn start)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

1. Change zoom level (zoom in or zoom out) via hot key or via `View` menu.
2. Reset zoom by press `Ctrl` + `0`
3. Click on room name or user name in sidebar -> show blank screen

Screen Shot 2021-01-04 at 10 55 57

4. Change zoom level again, app show normal

### Current Behavior

Show blank screen

### Expected Behavior

Use app normal

### PR DESCRIPTION
**Pull request by vuongtaquoc**
Closes #1936

It happens with webview. I fixed it by just zooming for webview content.

### CODE REVIEW

File: src/ui/main/menuBar.ts [hunk 1]
```diff
@@ -361,15 +365,20 @@ const createViewMenu = createSelector(
...
             browserWindow.showInactive();
           }
           browserWindow.focus();
-          if (browserWindow.webContents.zoomLevel >= 9) {
-            return;
+          const url = typeof currentView === 'object' ? currentView.url : null;
+          if (url) {
+            const guestWebContents = getWebContentsByServerUrl(url);
+            const zoomLevel = guestWebContents?.getZoomLevel();
+            if (zoomLevel && zoomLevel >= 9) {
```
Comment (ggazzo) [inline src/ui/main/menuBar.ts:376]:
```suggestion
            if (!Number.isInteger(zoomLevel) || zoomLevel >= 9) {
```

File: src/ui/main/menuBar.ts [hunk 2]
```diff
@@ -361,15 +365,20 @@ const createViewMenu = createSelector(
...
+              return;
+            }
+            (zoomLevel || zoomLevel === 0) &&
+              guestWebContents?.setZoomLevel(zoomLevel + 1);
```
Comment (ggazzo) [inline src/ui/main/menuBar.ts:380]:
```suggestion
            guestWebContents?.setZoomLevel(zoomLevel + 1);
```

**Review by ggazzo — CHANGES_REQUESTED** [review]

File: src/ui/main/menuBar.ts (hunk 1 above)
Comment (cazetto) [reply src/ui/main/menuBar.ts:376]: isNan?

**Review by ggazzo — APPROVED** [review]
